---
swagger: "2.0"
info:
 version: "2016-11-30T00:21:04Z"
 title: "visitu-main"
schemes:
- "https"
paths:
 /contacts/{proxy+}:
   options:
     consumes:
     - "application/json"
     produces:
     - "application/json"
     responses:
       200:
         description: "200 response"
         schema:
           $ref: "#/definitions/Empty"
         headers:
           Access-Control-Allow-Origin:
             type: "string"
           Access-Control-Allow-Methods:
             type: "string"
           Access-Control-Allow-Headers:
             type: "string"
     x-amazon-apigateway-integration:
       responses:
         default:
           statusCode: "200"
           responseParameters:
             method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
             method.response.header.Access-Control-Allow-Headers: "'Visitu-Volunteer-School-Code,Visitu-Origin,Visitu-UUID,Visitu-User,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
             method.response.header.Access-Control-Allow-Origin: "'*'"
       requestTemplates:
         application/json: "{\"statusCode\": 200}"
       passthroughBehavior: "when_no_match"
       type: "mock"
   x-amazon-apigateway-any-method:
     responses: {}
     x-amazon-apigateway-integration:
       responses:
         default:
           statusCode: "200"
       uri: http://https://47hpnauhk9.execute-api.us-east-1.amazonaws.com/Stage/contacts/{proxy}
       requestParameters:
         integration.request.path.proxy: "method.request.path.proxy"
       passthroughBehavior: "when_no_match"
       httpMethod: "ANY"
       cacheNamespace: "5iktnr"
       cacheKeyParameters:
       - "method.request.path.proxy"
       type: "http_proxy"