AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetContacts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getContacts
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /contacts
            Method: get
  CreateContact:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.createContact
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactTable
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /contacts
            Method: post
  CheckRecentOrders:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.checkRecentOrders
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactTable
          TWITTER_CONSUMER_KEY: 9u932FTpJwrlZRwJJwR1GExpa
          TWITTER_CONSUMER_SECRET: ws5lmrgDwLH4wnhgcjKMgg9cKA8r7oBTEVpftoUyXzsrjv6oWx
          TWITTER_ACCESS_TOKEN_KEY: 781576620574334976-IoIXK9RyHn8YweUzRusSwozRePXFqRI
          TWITTER_ACCESS_TOKEN_SECRET: Bxv8p2XJHlzcI6WPhxBXbV7kUcXqt2k9niamkpazV6PG4
      Events:
        CheckOrdersScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
  ContactTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
          Name: phoneNumber
          Type: String
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5